checks:
  java: true
filter:
  excluded_paths:
    - src/test/*
build_failure_conditions:
  - 'elements.rating(<= B).new.exists'           # No new classes/methods with a rating of B or worse
  - 'project.metric("scrutinizer.quality", < 9)' # Code Quality Rating drops below 9
