language: java
matrix:
  include:
    - os: linux
      sudo: false
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - oracle-java8-installer
    - os: linux
      sudo: false
      jdk: openjdk8
    - os: osx
      osx_image: xcode9.1
cache:
  directories:
  - .autoconf
  - $HOME/.m2
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then source .travis/start_xvfb.sh; fi
script:
  - mvn license:check
  - mvn formatter:validate
  - mvn cobertura:cobertura
after_success:
  - mvn coveralls:report
